name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format Rust code
        run: cargo fmt --all -- --check
